compdef g=git
compdef _git gst=git-status
compdef _git gl=git-pull
compdef _git gup=git-fetch
compdef _git gp=git-push
compdef _git gdv=git-diff
compdef _git gc=git-commit
compdef _git gc!=git-commit
compdef _git gc=git-commit
compdef _git gca!=git-commit
compdef _git gsw=git-switch
compdef _git gr=git-remote
compdef _git grv=git-remote
compdef _git grmv=git-remote
compdef _git grrm=git-remote
compdef _git grset=git-remote
compdef _git grset=git-remote
compdef _git gb=git-branch
compdef _git gba=git-branch
compdef gcount=git
compdef _git gcp=git-cherry-pick
compdef _git glg=git-log
compdef _git glgg=git-log
compdef _git glgga=git-log
compdef _git gss=git-status
compdef _git ga=git-add
compdef _git gm=git-merge
compdef git-svn-dcommit-push=git
compdef ggpull=git
compdef ggpush=git
compdef ggpnp=git
